### ISSUE TITLE
Chapter Grid Formatting/Content

### ISSUE THREAD

**Issue by kyogrekube** [RPI-Fraternity-Sorority-Commons-Website/FSC-Website#9]
The chapter grid page below is missing some organizations, such as Phi Delta Psi, Omega Phi Beta, and potentially others. The chapters are also currently not ordered in a very good way.

The page should instead have 4 sections for headers: Interfraternity Council Chapters, Panhellenic Chapters, Multicultural Chapters, and Professional Chapters. These should go directly above a grid not unlike the current one that displays only chapters in each of the councils. These should then be ordered alphabetically and on rows where there are not 4 organizations, center them properly.

**Comment by sadam-04** [comment]
Do you have a branch open for this?
